version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-net
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/t2
      - FRONTEND_ORIGIN=http://frontend:8080
    image: recipe-backend
    networks:
      - my-net

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - backend=http://localhost:8000
    image: recipe-frontend
    networks:
      - my-net
networks:
  my-net:
    driver: bridge

volumes:
  mongo_data:
