version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-net
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    image: recipe-backend
    networks:
      - my-net

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    image: recipe-frontend
    networks:
      - my-net
networks:
  my-net:
    driver: bridge

volumes:
  mongo_data:
